import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'
import Providers from '@/components/Providers'
import { Toaster } from 'react-hot-toast'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Talk with PDF',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <Providers>  
        {/* Wrapping in react-query */}
        <html lang="en">
          <body className={inter.className}>{children}</body>
          <Toaster/> {/* Used to create Alerts */}
        </html>
      </Providers>
    </ClerkProvider>
  )
}
